/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package anagram

import mu.KotlinLogging

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

private val logger = KotlinLogging.logger {}

fun main(args: Array<String>) {
    if (args.size != 2) {
        println("Usage: kotlin AnagramChecker <text1> <text2>")
        return
    }

    val text1 = args[0]
    val text2 = args[1]

    val checker = buildAnagramCheckerApp()

    if(checker.check(text1, text2).matchFound){
        println("Anagram found: $text1, $text2")
    }else{
        println("$text1, $text2 is not an anagram")
    }
}


fun buildAnagramCheckerApp(): AnagramChecker =
    AnagramChecker(DefaultStringToCharCounter(AnagramStringNormalizer()))

